# Generated by Django 5.1.1 on 2025-05-26 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_funding', models.DateField()),
                ('company_phone', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=255, unique=True)),
                ('company_country', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=200)),
                ('company_type_profile', models.CharField(max_length=50)),
                ('company_website', models.CharField(max_length=200)),
                ('company_social_media', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_funding', models.DateField()),
                ('organization_phone', models.CharField(max_length=50)),
                ('organization_email', models.EmailField(max_length=255, unique=True)),
                ('organization_country', models.CharField(max_length=30)),
                ('organization_address', models.CharField(max_length=200)),
                ('organization_type_profile', models.CharField(max_length=50)),
                ('organization_website', models.CharField(max_length=200)),
                ('organization_social_media', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_age', models.IntegerField()),
                ('user_phone', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=255, unique=True)),
                ('user_country', models.CharField(max_length=30)),
                ('user_type_profile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companydata')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrganizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizationdata')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userdata')),
            ],
        ),
    ]
