# Generated by Django 5.1.1 on 2025-05-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='company_password',
            field=models.CharField(default='abc', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='organization_password',
            field=models.CharField(default='abc', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_password',
            field=models.CharField(default='abc', max_length=16),
            preserve_default=False,
        ),
    ]
