# Generated by Django 5.1.1 on 2025-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userdata_user_address_alter_userdata_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_social_media',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_type_profile',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
