# Generated by Django 5.1.1 on 2025-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userdata_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address_user',
            field=models.CharField(default='por ahi', max_length=200),
            preserve_default=False,
        ),
    ]
