# Generated by Django 5.1.1 on 2025-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userdata_user_address_alter_userdata_user_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_pieces_name', models.CharField(max_length=200)),
                ('budget_pieces_year', models.IntegerField()),
                ('budget_pieces_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_sponsorships', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_ticket_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_marketing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_costumes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_set_design', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_art_design', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_music', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_lighting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_sound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_transportation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_accommodation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_miscellaneous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_rental', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_pieces_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PiecesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces_start_date', models.DateField()),
                ('pieces_submission_date', models.DateField()),
                ('pieces_name', models.CharField(max_length=200)),
                ('pieces_director', models.CharField(max_length=200)),
                ('pieces_cast', models.CharField(max_length=200)),
                ('pieces_description', models.TextField()),
                ('pieces_duration', models.IntegerField()),
                ('pieces_genre', models.CharField(max_length=30)),
                ('pieces_year', models.IntegerField()),
                ('pieces_website', models.CharField(max_length=200)),
                ('pieces_social_media', models.CharField(max_length=200)),
                ('pieces_trailer', models.CharField(blank=True, max_length=200, null=True)),
                ('pieces_poster', models.ImageField(blank=True, null=True, upload_to='pieces_posters/')),
                ('pieces_video', models.FileField(blank=True, null=True, upload_to='pieces_videos/')),
            ],
        ),
    ]
