# Generated by Django 5.1.1 on 2025-06-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_budgetdata_piecesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_expense_pieces_name', models.CharField(max_length=200)),
                ('budget_expense_pieces_year', models.IntegerField()),
                ('budget_expense_pieces_marketing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_costumes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_set_design', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_art_design', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_music', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_lighting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_sound', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_transportation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_accommodation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_miscellaneous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_rental', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_expense_pieces_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetIncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_income_pieces_name', models.CharField(max_length=200)),
                ('budget_income_pieces_year', models.IntegerField()),
                ('budget_income_pieces_sponsorships', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_income_pieces_ticket_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_income_pieces_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='BudgetData',
        ),
    ]
