# Generated by Django 5.1.1 on 2025-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_budgetexpensedata_budgetincomedata_delete_budgetdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetincomedata',
            name='budget_income_pieces_sponsorships',
        ),
        migrations.RemoveField(
            model_name='budgetincomedata',
            name='budget_income_pieces_ticket_sales',
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_donations_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_donations_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_sponsorships_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_sponsorships_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_state_subsidies_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_state_subsidies_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_ticket_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='budgetincomedata',
            name='budget_income_pieces_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
