# Generated by Django 5.1.1 on 2025-06-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_budgetincomedata_budget_income_pieces_sponsorships_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetincomedata',
            old_name='budget_income_pieces_subtotal',
            new_name='budget_income_pieces_donations_subtotal',
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_sponsorships_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_state_subsidies_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetincomedata',
            name='budget_income_pieces_ticket_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
