# Generated by Django 5.1.1 on 2025-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_budget_income_pieces_subtotal_budgetincomedata_budget_income_pieces_donations_subtotal_and_mo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_accommodation',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_art_design',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_costumes',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_fees',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_food',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_lighting',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_marketing',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_miscellaneous',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_music',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_production',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_rental',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_set_design',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_sound',
        ),
        migrations.RemoveField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_transportation',
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_accommodation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_accommodation_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_accommodation_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_art_design_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_art_design_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_art_design_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_costumes_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_costumes_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_costumes_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_fees_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_fees_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_fees_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_food_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_food_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_food_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_lighting_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_lighting_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_lighting_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_marketing_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_marketing_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_marketing_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_miscellaneous_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_miscellaneous_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_miscellaneous_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_music_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_music_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_music_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_production_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_production_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_production_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_rental_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_rental_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_rental_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_set_design_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_set_design_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_set_design_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_sound_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_sound_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_sound_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_transporation_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_transportation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_transportation_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='budgetexpensedata',
            name='budget_expense_pieces_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
