# Generated by Django 5.1.1 on 2025-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_budgetexpensedata_budget_expense_pieces_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
