# Generated by Django 5.1.1 on 2025-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userdata_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='organizationdata',
            name='organization_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization_images/'),
        ),
    ]
